#!/bin/env bash
set -e # without this my script may continue running even after something goes wrong.
# sudo pacman -S\
#     pipewire\
#     wireplumber\
    # wireplumber\
    # pipewire-pulse\
    # pavucontrol\
#     --noconfirm
# sudo pacman -S\
#   syntax-highlighting\
#     --noconfirm

# Install zinit: plugin manager for zshell
#bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"

# Powerlevel with ohmyzsh
# yay -S --noconfirm zsh-theme-powerlevel10k-git
# echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc
  # lazydocker\
  # postman-bin\
  # Dolphin\
# yay -S\
#   thunar\
#   --noconfirm
sudo pacman -S\
  obsidian\
  --noconfirm
